apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: flux-system
spec:
  releaseName: minecraft
  targetNamespace: minecraft
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: itzg-minecraft-server-charts
        namespace: flux-system
      version: "5.1.1"
  interval: 1h
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    force: true
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    minecraftServer:
      eula: "TRUE"
      version: "1.21.11"
      type: "FORGE"
      forgeVersion: "1.21.11-61.0.10"
      forgeInstallerUrl: https://maven.minecraftforge.net/net/minecraftforge/forge/1.21.11-61.0.10/forge-1.21.11-61.0.10-installer.jar
      serviceType: LoadBalancer
      loadBalancerIP: 172.21.0.173
      servicePort: 25565
      # firewall port forwarding:
      # WAN 25565 TCP > 172.21.0.173 25565 TCP
      downloadModpackUrl: https://mediafilez.forgecdn.net/files/7558/573/All%20the%20Mods%2010-5.5.zip
      removeOldMods: true
      memory: 10240M
      jvmOpts: "-Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      # jvmXXOpts: "-XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=8M -XX:G1HeapWastePercent=5 -XX:G1MaxNewSizePercent=40 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1NewSizePercent=30 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -XX:MaxGCPauseMillis=200 -XX:MaxTenuringThreshold=1 -XX:SurvivorRatio=32"
    persistence:
      storageClass: "synology-ext4-retain"
      dataDir:
        enabled: true
        size: 10Gi
    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 10Gi
        cpu: 2
