apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: flux-system
spec:
  releaseName: minecraft
  targetNamespace: minecraft
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: itzg-minecraft-server-charts
        namespace: flux-system
      version: "5.1.1"
  interval: 1h
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    force: true
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    workloadAsStatefulSet: true
    strategyType: RollingUpdate
    minecraftServer:
      eula: "TRUE"
      version: "1.21.1"
      type: "CURSEFORGE" # auto-downloads mods + NeoForge
      memory: 8G
      # jvmXXOpts: "-XX:+UseZGC -XX:+UseCompactObjectHeaders"
      serviceType: LoadBalancer
      loadBalancerIP: 172.21.0.173
      servicePort: 25565
      # firewall port forwarding:
      # WAN 25565 TCP > 172.21.0.173 25565 TCP
      # downloadModpackUrl: https://mediafilez.forgecdn.net/files/7558/613/ServerFiles-5.5.zip
      cfServerMod: "https://mediafilez.forgecdn.net/files/7558/613/ServerFiles-5.5.zip"
      removeOldMods: true
      icon: https://github.com/emerconn/homelab/blob/main/k8s/flux/clusters/tal-clu-1/apps/minecraft/usa.png?raw=true
      whitelist: "NemmyBangz"
      motd: "nemmy lives here"
    persistence:
      storageClass: "synology-ext4-retain"
      dataDir:
        enabled: true
        Size: 15Gi
    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 8Gi
        cpu: 2
