apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: flux-system
spec:
  releaseName: minecraft
  targetNamespace: minecraft
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: itzg-minecraft-server-charts
        namespace: flux-system
      version: "5.1.1"
  interval: 1h
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    force: true
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    minecraftServer:
      eula: "TRUE"
      version: "1.21.11"
      type: "FORGE"
      forgeVersion: "1.21.11-61.0.10"
      forgeInstallerUrl: https://maven.minecraftforge.net/net/minecraftforge/forge/1.21.11-61.0.10/forge-1.21.11-61.0.10-installer.jar
      serviceType: LoadBalancer
      loadBalancerIP: 172.21.0.173
    persistence:
      storageClass: "synology-ext4-retain"
      dataDir:
        enabled: true
        Size: 10Gi
