apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
resources:
- helm-release.yaml
- helm-values.yaml
- namespace.yaml

configMapGenerator:
- name: helm-values
  files:
  - values.yaml=helm-values.yaml
  options:
    disableNameSuffixHash: true
