apiVersion: v1
kind: Secret
metadata:
    name: cf-api-key
    namespace: minecraft
type: Opaque
stringData:
    cf-api-key: ENC[AES256_GCM,data:0EmQd+AB6ytEqdq6UaeMv8cJnOZAP/vEX8WYp5Cgx+xeKCvyxWvBR8BjB6uG9dV355haOTxFNZSQ+cKakn/7,iv:pO2SqPMMEKpUdCWuHhuGry0uoennYf+0nXIX4VuwZiw=,tag:BwXy4sYmZFbsbIkVnN+dnQ==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T05:18:24Z"
    mac: ENC[AES256_GCM,data:AUu0DltrmApG1AqsPm8UmcIWl/UG/X2+y+d36ghXbXjPLlzpy+8fOaWuC7E2mADUnZ6N/iIkfafDPAZ17DGoRSWI32/BX2ZlBrfLNG9UhpE9E5BI7cvjLSxfmYDjc1YA0WisWjmWwUiyk/BlteagJIvQ51Rb0MKDr+tG2YyXn+o=,iv:DZbctVeOdtQIbb/3LLFsqbvO0BS1G61C63sma0Vz08A=,tag:dngTUnh4hzVH3ITFdCDs1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
