apiVersion: v1
kind: Secret
metadata:
    name: cf-api-key
    namespace: minecraft
type: Opaque
stringData:
    cf-api-key: ENC[AES256_GCM,data:D7KV3hLgDw2BvxIHYVnIHbCO/HPRZEbHGZ+9clgMR83DrF6CxarcTnAmwaglR74EVW4BbuyHVEUvBh70DQ==,iv:Q2KN0o9Nu+2vIeUE4r7OHayhHQ2As0fGE2y2Z9kZfi4=,tag:/jEQpArFyKwkvST5OsTeYQ==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T05:12:24Z"
    mac: ENC[AES256_GCM,data:JtYe94ao8dk0LBn5/LEnHhzm7az+U5/KFrN74r1Bn289kSShHAt3tiTOEaMvXsZqeQUHbc2Hm90pEFYKQk9HxbVWCmaBRUdwyR9tngl+guU0GDbyImLG0itBNBvQReas3q1lvWJzEmyWtMrSo+aI6fs3qHNbmPsieebN3Ak7gC0=,iv:67WIm2agbmKw1EgdyYSfGAgEZw7ZalTRamNOYTjJRJw=,tag:jSXX2tmlkFfv/QI9mTHKJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
