apiVersion: v1
kind: Secret
metadata:
    name: cf-api-key
    namespace: minecraft
type: Opaque
stringData:
    cf-api-key: ENC[AES256_GCM,data:mcB8BFVdi2Tqd3zy31K11T+gsNmMMubQV/c73Q+pA8cyi+8WOS3xolnvXQrOKPAgkwfsIXDUPhlzlmSF,iv:J3E0g30MfyfCg5RTbXyOd9IPwou1OPHHg8vWzxidP1w=,tag:LJc0YNsjKR2KaNCVBWZwVA==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T05:23:56Z"
    mac: ENC[AES256_GCM,data:L7z5FxgtPrAZP6sFDcXDv7d0TerrlU8XVwiQqifjgHHS+jbqBJwEj/89YnG2YVRu0qG+UH7GBJF5mXSgdMJKacn1laUlXPuDXlphBmCw15rTGpOlq/8Nki0PW1id26ZT5cwog5D9dt2feXdTf7FsIDV66pUF4c4uh7pdWjljsjU=,iv:wmYG3a14IZ3F3kf4A8hXbDdWZLWGsrJK0dVWbTK9iFU=,tag:rspuxPqNxAB8bKVMgsp23g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
