apiVersion: v1
kind: Secret
metadata:
    name: cf-api-key
    namespace: minecraft
type: Opaque
stringData:
    cf-api-key: ENC[AES256_GCM,data:D7KV3hLgDw2BvxIHYVnIHbCO/HPRZEbHGZ+9clgMR83DrF6CxarcTnAmwaglR74EVW4BbuyHVEUvBh70DQ==,iv:Q2KN0o9Nu+2vIeUE4r7OHayhHQ2As0fGE2y2Z9kZfi4=,tag:/jEQpArFyKwkvST5OsTeYQ==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T05:14:51Z"
    mac: ENC[AES256_GCM,data:NrV9JZnKSm6/urEZ+SHch4x6CfAXQcs2slOr1wc5XPVpvbGHlzPV4dsd3pB5WEqJ9gfFNgIJXTT8PhFzxvJ5DmWyypK0eq3VHB127UpNuHYqWyagu1RD7TTxNHt9T4IRcYx7ko1Uz6uFFMbN/9xlvIGPouHc/YegMPtXVmO/NSA=,iv:SLLUQktNvRMN1arsg+Wxd/VU8yqS3XNhBj+AO2fW0+Y=,tag:IE7//uKI5J9SIqPDSOlJ0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
