apiVersion: v1
kind: Secret
metadata:
    name: cf-api-key
    namespace: minecraft
type: Opaque
stringData:
    cf-api-key: ENC[AES256_GCM,data:+24b5dPjd6Tka4cRNyBg8uuXwvGnRRtLIG0pGBwqKQg9CFn8zeWKWhta5Cuj4eITACgdUHgwpYJwPHe2sQ==,iv:7wiPPmMVvUyUik9kGa4HySTI8IkH+6CSCdjY1NgenlI=,tag:Xxxqyg/eA5EcINeUItzxWQ==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T05:29:03Z"
    mac: ENC[AES256_GCM,data:MG0dQnQY6AJCPKmB7NGP5WDVhspZPpdNcn+6vzgTK3zXpfyYnsWisn83S9UYYxBdm3pUNteTcwWNIt4fWLU7atgoTgMnIXtAO0euPqe3TlRs9Sd0aQvYHJBGVvtVXz9fgDViihQzlEOP9rXM65KDMYVHUWf4qTslnyVdhV0Vtug=,iv:HMgxkMbugEnx7vKuFFozNMaXXiprRsDENfQQ33Ov54s=,tag:sg8txs9npG9kaUFLEDGnuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
