apiVersion: v1
kind: Secret
metadata:
    name: cf-api-key
    namespace: minecraft
type: Opaque
stringData:
    cf-api-key: ENC[AES256_GCM,data:AWo9LLv/fx09PrG+DPKalD7VLhljcPN5xvbnc1xLYyoIHhmDTB9XrFs3SmDh/JhFS+GDqMUf5Nw55sz+,iv:vuk4RwzGFJvoLbu4hmtn62lzZ4XXbODgEpdb4su6qpY=,tag:XNuz4tCmT5DAkvu01fD0sA==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T05:04:43Z"
    mac: ENC[AES256_GCM,data:D+GhitzAFKZOIvQsSSuHvisbs24P+mLRA3kcWHwBA7atgT7bl56do4KFRV8yFMxl/ngibURsx/6BCqQh618AdHqgaxowMl2cQPuBI+URBMMcW1Y3FWBIXBbo+i2z2bPLnJSuQMXZbYjZmpXL1RsvkZjkQ/camg7EWQgFXT3clwU=,iv:izf88GEOEIcQNZQgoY3s+r7VAc/urV2e/Ac2xVKpiQ0=,tag:nr7j4SbHEb8KUCx0kGW1/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
