apiVersion: v1
kind: Secret
metadata:
    name: curseforge-api-key
    namespace: minecraft
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:rWLU3en1Ak21a6inDoCozczqsWaU0rt95baBqJPWzcYpgqtXUtwEU9i2bedev42mB6JecbeLZjSqVMM2,iv:gl8iYE9V94RN5ydqPD3f1CFfU34nzsk0tlta704l6Kw=,tag:glWjPNNtsGnOb2ISGLJepA==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T04:52:21Z"
    mac: ENC[AES256_GCM,data:+548LVOAyYKXbT0yALVKY0zHd52WO1UyMSu2exiKTRbKk5D53SZbjSwCO2CGNvERUu0UNAGlyBnQXkd3mROwWfCxta5pRkaQuF8JRJi8r5T/u4pU2mbp7ffKmEiNrQaGy7VvQtzuPa66r9rVY9A2pbUophRthKQG8K7O1lnBQpw=,iv:ks7MdpJ2RgoD64nt4J6iBTuyoud1sZtIIdFqy5AL2C0=,tag:KjOMbFIcoVM0XBsf9IMFuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
