apiVersion: v1
kind: Secret
metadata:
    name: cf-api-key
    namespace: minecraft
type: Opaque
stringData:
    cf-api-key: ENC[AES256_GCM,data:xtkNuGq4VS8LqgWut8xUM5n4gM5f4+N9NIbHGC+AErUMUBvceUXb98rlk1lbpf0btCXVWf9Ic2c9rCbE,iv:ApNP7w9e8LDKTGfpT9P6vxJeHLzxeLqgUT/wbni7fxA=,tag:ZBFc2YFG4m06hI6+Mj/osA==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T05:07:55Z"
    mac: ENC[AES256_GCM,data:zXvftzeUzr5suxBC2c3kh58jKdpETYEJhvmMijFiidwbrtUwTIFQrsx3uhafOwAPbaevdNWXRluzzhRDuvtJESPKOe1isYUCdLnMayX8agv2RaI4O5nrRZ3zbfo6raUMqWcfJSPqUijy//onrV4swpuzFYn1L0UNtIaPlMiZzuE=,iv:VVGTxGafWTjKj1svY8dRav/sAVc6CnFlrkjJUgj7cOA=,tag:Y+3zI3iIdi9Aqd8IsGd+vw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
