apiVersion: v1
kind: Secret
metadata:
    name: curseforge-api-key
    namespace: minecraft
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:hmARzK8t0v4gvZCaMR+Ymh2Z5xvUsR+Laa1udCXMn2DxzBBJ,iv:ujrzTP2Q7xCy+u1IL2nTMeI7neUGSfvNF078NtxLAnk=,tag:5G2GmlKaxg8FBR2kpZg2NA==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T04:49:13Z"
    mac: ENC[AES256_GCM,data:jC/+VWJXnqAJjRFth6riifB7EMcWMZb2iO4QoOB7RuQwadqC1K1rgfgfLo+EYtUItugFL8JYFieYWiit9Htv92aZ1I0rnyriASmT9Uw0bbGaF4PqYWYmUuhn94PNDkdqcnYM0tgu0oHO3T3z8rXqP+OM3DvqGYgyep7fM8jS8AY=,iv:jPs4gcnrf6YYyoTv1nS0j3BOGQpmjNQf9/dPV+ia9Cw=,tag:Sb82i9jAfj+nCB2uWfG4RQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
