apiVersion: v1
kind: Secret
metadata:
    name: cf-api-key
    namespace: minecraft
type: Opaque
stringData:
    cf-api-key: ENC[AES256_GCM,data:TFG2TXN6/C1vzdja/1tS/XffJfkVLPRkLNQDoebxNqhRWcjU2yV7Ozt3JyrVyKb8Uiq0SVV+KsEoM8REZrY7,iv:EyPrUz9kFotbbFnZsg5i6oWFC6gvhxnl7sEBgP181HQ=,tag:Kjp94H1QpaV/ayWMu+immg==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T05:22:14Z"
    mac: ENC[AES256_GCM,data:HAkRSaa3eiNg0cacTM6RZB4eJW5ShmtQQFgG6ESRUbNEqMfbVI/VyWn5EPtCsjGsgSLEbu3nkArJy7S8wXCGbx9yem+4dcnI4adVW1gPJIwOEuq4scJyUb6v+Bp1nYxjFtjFYN1zYCtkQurMCGDOyzDE1Kxos9he37uA0rwAo8s=,iv:/5ddJqR4gz8dy7KXvA0Dx7CFitsB14WodnRzB+bGgS8=,tag:VeY82ih6R7a4ikSWIFFpCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
