apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: flux-system
spec:
  releaseName: minecraft
  targetNamespace: minecraft
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: itzg-minecraft-server-charts
        namespace: flux-system
      version: "5.1.1"
  timeout: 10m
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
    cleanupOnFail: true
  values:
    workloadAsStatefulSet: true
    strategyType: RollingUpdate
    minecraftServer:
      eula: "TRUE"
      version: "1.21.1"
      type: "CURSEFORGE"
      memory: 10G
      serviceType: LoadBalancer
      loadBalancerIP: 172.21.0.173
      servicePort: 25565
      # firewall port forwarding:
      # WAN 25565 TCP > 172.21.0.173 25565 TCP
      cfServerMod: https://mediafilez.forgecdn.net/files/7558/613/ServerFiles-5.5.zip
      removeOldMods: true
      whitelist: "NemmyBangz, Narutoooooooo, kinowithluv, VII_Rook, AntacusBantacus"
      ops: "NemmyBangz"
      motd: "nemmy lives here"
      rcon:
        enabled: true
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: mc.emerconn.com
    persistence:
      storageClass: synology-ext4-retain
      dataDir:
        enabled: true
        Size: 15Gi
    resources:
      requests:
        cpu: 2
        memory: 10Gi
      limits:
        cpu: 7
        memory: 10Gi
    livenessProbe:
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 50
      initialDelaySeconds: 180
    readinessProbe:
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 50
      initialDelaySeconds: 180
    extraEnv:
      USE_MEOWICE_FLAGS: true
